### ISSUE TITLE
Question: why .mjs extension is required with yarn workspaces and babel?

### ISSUE THREAD

**Issue by fusionstrings** [jspm/rollup-plugin-jspm#9] opened 2019-07-09 10:48 UTC
So far I am delighted with usefulness of the plugin. I have a use case where I need to integrate it with yarn workspaces.
I am having issue with using this plugin with [Yarn Workspace](https://yarnpkg.com/en/docs/workspaces) in conjunction of `.js` file extension and babel. 

Example repo https://github.com/fusionstrings/brandy.
- [no-workspace branch](https://github.com/fusionstrings/brandy/tree/no-workspace) builds fine. It uses `.js` extension. **_This branch doesn’t use yarn workspace_**
- [master branch](https://github.com/fusionstrings/brandy/tree/master) builds fine. It uses `.mjs` extension. **_This branch uses yarn workspace._**
- [error-with-workspace branch](https://github.com/fusionstrings/brandy/tree/error-with-workspace) doesn’t build with following error. It uses (mix) of`.js` extension. Although mix doesn’t matter, error is same even if all the workspace files are `.js`. **_This branch uses yarn workspace._**

The reason is https://babeljs.io/docs/en/options#sourcetype.

```sh
[!] (plugin jspm-rollup) SyntaxError: /Users/dilip/github/@fusionstrings/brandy/packages/ansac/components/ansac.js: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.

> 1 | import React from 'https://dev.jspm.io/react';
    | ^
  2 | 
  3 | function Ansac() {
  4 |   return (
../ansac/components/ansac.js (1:0)
SyntaxError: /Users/dilip/github/@fusionstrings/brandy/packages/ansac/components/ansac.js: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.

> 1 | import React from 'https://dev.jspm.io/react';
```
I am raising this issue as a question on why `rollup-plugin-jspm` expects `.mjs` with workspace and doesn’t care otherwise?

**Comment by guybedford** [comment] 2019-07-19 22:55
Am I right in thinking the underlying issue here might be that the `"type": "module"` in the package.json file is not properly being picked up by the node_modules resolution for jspm (which is implemented in jspm-resolve as a fallback path)?

One way to check this can be to run jspm-resolve directly as an API, and try resolving a package in the workspace:

```js
const jspmResolve = require('jspm-resolve');
const { resolved, format } = jspmResolve.sync('pkgname', process.cwd());
console.log(format);
```

The above will tell you the detected module format, from which you should be able to see if it's detecting it incorrectly.

That would at least make this clearly a jspm-resolve bug!

At that point we can create a test case there and see what needs to be done to put together the fix.

Let me know if that sounds like a sensible route forward here.

**Comment by fusionstrings** [comment] 2019-07-19 23:58
I created a file at the root of the workspace, added the said code but I am getting ùndefined` in all three scenarios.

**Comment by guybedford** [comment] 2019-07-20 00:05
It sounds like the resolution isn't actually working at all then (`resolved` is likely `undefined` I expect). In this case you may need to ensure that `process.cwd()` is the same folder as where `node_modules` is located, and that `'pkgname'` is the correct package name you want to resolve.

**Comment by fusionstrings** [comment] 2019-07-20 00:48
yeah, I've added file at the root https://github.com/fusionstrings/brandy/blob/master/brand.js

**Comment by guybedford** [comment] 2019-07-24 23:23
@fusionstrings there seem to be two issues there:

1. You need to install `@jspm/resolve` not `jspm-resolve`
2. The package `ansac` has a `"main": "main.js"` when it should be `"main": "main.mjs"`.

With the above changes it seems to be working for me.

**Comment by fusionstrings** [comment] 2019-07-25 19:07
@guybedford Thanks for pointing out. I've corrected the main fields and imports. As a result I can now get the resolve status but as you suspected, it's resolving as `commonjs` for `.js` extensions. 

Following is the branch which has the issue. Master branch builds as all the files are in `.mjs`.

https://github.com/fusionstrings/brandy/tree/error-with-workspace

you may run `yarn && yarn resolve` to see the resolution output.

**Comment by guybedford** [comment] 2019-07-28 21:44
Thanks, I finally see what you mean - the problem is that we don't support `"type": "module"` for `.js` files in `node_modules`. I've created an issue for this in https://github.com/jspm/jspm-resolve/issues/10.

**Closed by guybedford** 2019-07-28 21:44 UTC
